display_name = "Skeleton Library"
library_name = "skellib"
version = "0.0.1"
author = "Carla Coder"
author_email = "carla@codes.com"
license = "Open All The Things!"
url = "https://github.com/carlacoder/skellib"
description = "A Simple Skeleton Project for Python"
long_description = description
requires = []
